nguage: bash

sudo: false

addons:
  apt:
    sources:
    - debian-sid
    packages:
    - shellcheck

script:
 - bash -c 'shellcheck -e SC1090,SC1091,SC2015,SC2034,SC2154 $(egrep -lir "#\!/bin/bash" . | grep -v override)'

matrix:
  fast_finish: true
